apiVersion: v2
name: pyrra
# renovate: github=pyrra-dev/pyrra
appVersion: v0.10.0
version: 1.6.0
description: SLO manager and alert generator
sources:
  - https://github.com/pyrra-dev/pyrra
type: application
