---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pyrra.fullname" . }}
  namespace: {{ include "pyrra.namespace" . }}
  labels:
    {{- include "pyrra.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pyrra.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pyrra.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pyrra.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- include "pyrra.container.kubernetes" . | nindent 8 }}
        {{- include "pyrra.container.api" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.extraApiVolumes (and .Values.validatingWebhookConfiguration.enabled ($.Capabilities.APIVersions.Has "cert-manager.io/v1")) }}
      volumes:
        {{- if and .Values.validatingWebhookConfiguration.enabled ($.Capabilities.APIVersions.Has "cert-manager.io/v1") }}
        - name: certs
          secret:
            secretName: {{ include "pyrra.fullname" . }}-webhook-validation
        {{- end }}
        {{- with .Values.extraApiVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
