---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyrra.fullname" . }}
  namespace: {{ include "pyrra.namespace" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "pyrra.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: webhooks
      port: 9443
    - name: api
      port: 9444
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - name: op-metrics
      port: {{ .Values.service.operatorMetricsPort }}
      targetPort: {{ include "pyrra.operatorMetricsPort" . }}
  selector:
    {{- include "pyrra.selectorLabels" . | nindent 4 }}
